
name: test-operator-ci
on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      production:
        description: 'Click the checkbox for production images'
        default: false
        type: boolean
        required: false
env:
  IMAGE_VERSION: 'v0.9.1'
